# 服务配置
server:
  port: 8080
  servlet:
    context-path: /api

# Spring 配置
spring:
  application:
    name: netty-server

# Netty 配置
netty:
  host: 0.0.0.0  # 服务器绑定地址
  port: 8888  # 服务器端口
  boss-threads: 2  # boss 线程数
  worker-threads: 8  # worker 线程数，0 表示使用 Netty 默认值
  keep-alive: true  # 是否保持长连接
  backlog: 128  # 最大等待连接数
  reader-idle-time-seconds: 0  # 读空闲时间秒数
  writer-idle-time-seconds: 0  # 写空闲时间秒数
  all-idle-time-seconds: 10  # 所有空闲时间秒数
  max-lost-heartbeat: 3  # 最大丢失心跳次数
  boss-name-prefix: netty-boss-
  worker-name-prefix: netty-worker-