server:
  port: 8081
  servlet:
    context-path: /api

# Spring 配置
spring:
  application:
    name: netty-client

# Netty 配置
netty:
  # 客户端配置
  client:
    host: 127.0.0.1  # 服务器地址
    port: 8888  # 服务器端口
    reconnect-delay: 5  # 重连延迟(秒)
    connect-timeout: 5000  # 连接超时(毫秒)
    reader-idle-time-seconds: 0  # 读空闲时间秒数
    writer-idle-time-seconds: 0  # 写空闲时间秒数
    all-idle-time-seconds: 120  # 所有空闲时间秒数
    max-lost-heartbeat: 3  # 最大丢失心跳次数
    
  # 线程池配置
  thread:
    boss-name-prefix: netty-boss-
    worker-name-prefix: netty-worker-
    client-name-prefix: netty-client-

logUpload:
  isCompressed: true
  bankAccount:
    isDesensitized: true
    # This regex matches 12-19 digit bank account numbers
    regex: (?:^|[^0-9])([0-9]{4})([0-9]{4,11})([0-9]{4})(?:$|[^0-9])