server:
  port: 8081
  servlet:
    context-path: /api

# Netty 配置
netty:
  # 客户端配置
  client:
    host: 127.0.0.1  # 服务器地址
    port: 8888  # 服务器端口
    reconnect-delay: 5  # 重连延迟(秒)
    connect-timeout: 5000  # 连接超时(毫秒)
    
  # 线程池配置
  thread:
    boss-name-prefix: netty-boss-
    worker-name-prefix: netty-worker-
    client-name-prefix: netty-client-

# 日志配置
logging:
  level:
    root: info
    io.netty: warn
    org.springframework: warn
    com.example.nettydemo: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/netty-demo.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 7
